/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jgonvsuzzhbfebstzdjt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impnb252c3V6emhiZmVic3R6ZGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyMzc1NjQsImV4cCI6MjA3OTgxMzU2NH0.-1jfkvUJIukMv_VjUHFRL-PXlbKjOOlq_CYO07Pm_kY"