import { useState, useEffect } from 'react';
import { X, Calculator, DollarSign, Users, Briefcase, Clock, TrendingDown, Copy, Printer, Check } from 'lucide-react';
import { Dialog, DialogContent, DialogTrigger } from './ui/dialog';
import { Button } from './ui/button';
import { Slider } from './ui/slider';
import { Badge } from './ui/badge';

type ROICalculatorProps = {
  isOpen: boolean;
  onClose: () => void;
};

export function ROICalculator({ isOpen, onClose }: ROICalculatorProps) {
  // --- INPUTS ---
  const [employees, setEmployees] = useState(50);
  const [turnoverRate, setTurnoverRate] = useState(15); // 15% annual turnover
  const [avgSalary, setAvgSalary] = useState(45000); // Gross monthly CZK
  const [timeToFill, setTimeToFill] = useState(45); // Days to find replacement

  // --- CALCULATED METRICS ---
  const [metrics, setMetrics] = useState({
    departingEmployees: 0,
    recruitmentCost: 0,
    rampUpCost: 0,
    managerTimeCost: 0,
    quietQuittingCost: 0,
    totalAnnualLoss: 0
  });

  const [copied, setCopied] = useState(false);

  useEffect(() => {
    // 1. Počet odchodů za rok
    const departing = Math.ceil(employees * (turnoverRate / 100));

    // 2. Náklady na nábor (Direct Recruiting Costs)
    // Inzerce (Jobs.cz/LI) + HR screening (50 CVs * 10min) + Admin
    // Avg cost per hire in CZ (non-agency) ~ 15,000 CZK internal cost + ads
    const costPerHire_Ads = 8000; 
    const costPerHire_HRTime = 5000; // cca 10-15h HR práce
    const totalRecruitment = departing * (costPerHire_Ads + costPerHire_HRTime);

    // 3. Manažerský čas (Interviewing & Training)
    // 3 kola pohovorů x 1h x (Team Lead + Senior) + Onboarding support
    // Superhrubá mzda managera (cca 70k) -> hodinovka cca 600 CZK (nákladová)
    const managerHoursPerHire = 12; // 4h interviews + 8h onboarding mentoring
    const managerHourlyCost = 600;
    const totalManagerCost = departing * (managerHoursPerHire * managerHourlyCost);

    // 4. Lost Productivity (Ramp-up Time)
    // První 3 měsíce je člověk na 50% produktivitě.
    // Firma platí superhrubou (1.34) ale dostává 50%.
    // Ztráta = 3 * (Salary * 1.34) * 0.5
    const superGross = avgSalary * 1.34;
    const rampUpLossPerPerson = 3 * superGross * 0.5;
    const totalRampUp = departing * rampUpLossPerPerson;

    // 5. Tichý odchod (Quiet Quitting / Disengagement)
    // Gallup: Disengaged employee costs 18% of annual salary.
    // Předpoklad: 15% zaměstnanců je disengaged (mimo ty co odejdou)
    const disengagedCount = Math.floor((employees - departing) * 0.15);
    const annualSuperGross = superGross * 12;
    const quietQuittingLoss = disengagedCount * (annualSuperGross * 0.18);

    // TOTAL
    setMetrics({
      departingEmployees: departing,
      recruitmentCost: totalRecruitment,
      rampUpCost: totalRampUp,
      managerTimeCost: totalManagerCost,
      quietQuittingCost: quietQuittingLoss,
      totalAnnualLoss: totalRecruitment + totalRampUp + totalManagerCost + quietQuittingLoss
    });

  }, [employees, turnoverRate, avgSalary, timeToFill]);

  const formatCurrency = (val: number) => {
    return new Intl.NumberFormat('cs-CZ', { style: 'currency', currency: 'CZK', maximumFractionDigits: 0 }).format(val);
  };

  const copyReceipt = () => {
    const text = `
🧾 ECHO ANALYSIS: COST OF ATTRITION
-----------------------------------
Zaměstnanců: ${employees}
Fluktuace: ${turnoverRate}%
Průměrná mzda: ${formatCurrency(avgSalary)}
-----------------------------------
Odhadované ztráty (ročně):
1. Nábor a Inzerce: .... ${formatCurrency(metrics.recruitmentCost)}
2. Manažerský čas: ..... ${formatCurrency(metrics.managerTimeCost)}
3. Snížená produktivita: ${formatCurrency(metrics.rampUpCost)}
4. Tichý odchod (Hidden): ${formatCurrency(metrics.quietQuittingCost)}
-----------------------------------
CELKOVÁ ZTRÁTA: ${formatCurrency(metrics.totalAnnualLoss)}
-----------------------------------
Generated by Echo Telesales OS
    `;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-slate-950 border border-slate-800 w-full max-w-4xl rounded-2xl shadow-2xl overflow-hidden flex flex-col md:flex-row max-h-[90vh]">
        
        {/* LEFT PANEL: CONTROLS */}
        <div className="flex-1 p-8 overflow-y-auto">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-3 bg-indigo-500/20 rounded-xl border border-indigo-500/30">
              <Calculator className="w-6 h-6 text-indigo-400" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">ROI Calculator</h2>
              <p className="text-slate-400 text-xs uppercase tracking-wider">Turnover & Retention Analysis</p>
            </div>
          </div>

          <div className="space-y-8">
            {/* Input 1: Employees */}
            <div className="space-y-4">
              <div className="flex justify-between text-sm">
                <label className="text-slate-300 font-medium flex items-center gap-2">
                  <Users className="w-4 h-4 text-slate-500" /> Počet zaměstnanců
                </label>
                <span className="font-mono text-indigo-400 font-bold">{employees} lidí</span>
              </div>
              <Slider 
                value={[employees]} 
                min={10} 
                max={500} 
                step={5} 
                onValueChange={(val) => setEmployees(val[0])}
                className="py-2"
              />
            </div>

            {/* Input 2: Turnover */}
            <div className="space-y-4">
              <div className="flex justify-between text-sm">
                <label className="text-slate-300 font-medium flex items-center gap-2">
                  <TrendingDown className="w-4 h-4 text-slate-500" /> Roční fluktuace (%)
                </label>
                <span className="font-mono text-red-400 font-bold">{turnoverRate}% ({metrics.departingEmployees} lidí)</span>
              </div>
              <Slider 
                value={[turnoverRate]} 
                min={5} 
                max={50} 
                step={1} 
                onValueChange={(val) => setTurnoverRate(val[0])}
                className="py-2"
              />
            </div>

            {/* Input 3: Salary */}
            <div className="space-y-4">
              <div className="flex justify-between text-sm">
                <label className="text-slate-300 font-medium flex items-center gap-2">
                  <DollarSign className="w-4 h-4 text-slate-500" /> Průměrná hrubá mzda
                </label>
                <span className="font-mono text-emerald-400 font-bold">{avgSalary.toLocaleString()} Kč</span>
              </div>
              <Slider 
                value={[avgSalary]} 
                min={25000} 
                max={150000} 
                step={1000} 
                onValueChange={(val) => setAvgSalary(val[0])}
                className="py-2"
              />
            </div>
            
            <div className="p-4 bg-indigo-900/20 border border-indigo-500/20 rounded-lg text-sm text-indigo-200/80 leading-relaxed">
              <p>💡 <strong>Echo Insight:</strong> Při {turnoverRate}% fluktuaci se vám tým kompletně obmění každých {Math.round(100/turnoverRate * 10) / 10} let. Většina firem podceňuje "měkké" náklady na zaškolení.</p>
            </div>
          </div>
        </div>

        {/* RIGHT PANEL: THE RECEIPT */}
        <div className="w-full md:w-[420px] bg-slate-100 relative p-8 shadow-inner flex flex-col font-mono text-slate-800">
          
          {/* Paper Tear Effect Top */}
          <div className="absolute top-0 left-0 right-0 h-4 bg-[linear-gradient(45deg,transparent_75%,#f1f5f9_75%),linear-gradient(-45deg,transparent_75%,#f1f5f9_75%)] bg-[size:20px_20px] rotate-180 translate-y-[-10px]"></div>

          <div className="flex-1 flex flex-col gap-2">
            <div className="text-center border-b-2 border-dashed border-slate-300 pb-4 mb-2">
              <h3 className="text-2xl font-black tracking-tighter uppercase text-slate-900">COST ANALYSIS</h3>
              <p className="text-xs text-slate-500">Echo Intelligence Corp.</p>
              <p className="text-xs text-slate-400">{new Date().toLocaleDateString('cs-CZ')} • ID: #8821X</p>
            </div>

            {/* Items */}
            <div className="space-y-3 text-sm my-4">
              <div className="flex justify-between items-baseline">
                <span className="font-bold text-slate-600">NÁBOR & INZERCE</span>
                <span>{formatCurrency(metrics.recruitmentCost)}</span>
              </div>
              <div className="text-[10px] text-slate-500 leading-tight pl-2 border-l-2 border-slate-300">
                Jobs.cz, LinkedIn, HR screening CVs, administrativa.
              </div>

              <div className="flex justify-between items-baseline mt-4">
                <span className="font-bold text-slate-600">MANAŽERSKÝ ČAS</span>
                <span>{formatCurrency(metrics.managerTimeCost)}</span>
              </div>
              <div className="text-[10px] text-slate-500 leading-tight pl-2 border-l-2 border-slate-300">
                Příprava, 3 kola pohovorů, onboarding support.
              </div>

              <div className="flex justify-between items-baseline mt-4">
                <span className="font-bold text-slate-600">RAMP-UP (3 MĚSÍCE)</span>
                <span>{formatCurrency(metrics.rampUpCost)}</span>
              </div>
              <div className="text-[10px] text-slate-500 leading-tight pl-2 border-l-2 border-slate-300">
                Ušlá produktivita během zaškolení (50% výkon za 100% ceny).
              </div>

              <div className="flex justify-between items-baseline mt-4 opacity-75">
                <span className="font-bold text-slate-600">TICHÝ ODCHOD</span>
                <span>{formatCurrency(metrics.quietQuittingCost)}</span>
              </div>
              <div className="text-[10px] text-slate-500 leading-tight pl-2 border-l-2 border-slate-300 opacity-75">
                Skryté náklady na disengaged zaměstnance (Gallup model).
              </div>
            </div>

            {/* Total */}
            <div className="mt-auto border-t-2 border-dashed border-slate-800 pt-4">
              <div className="flex justify-between items-end mb-1">
                <span className="text-lg font-black uppercase">Roční Ztráta</span>
              </div>
              <div className="text-4xl font-black text-red-600 tracking-tighter">
                {formatCurrency(metrics.totalAnnualLoss)}
              </div>
              <p className="text-[10px] text-slate-400 mt-2 text-center uppercase tracking-widest">
                * Odhadované náklady bez Retention Toolu
              </p>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="mt-6 grid grid-cols-2 gap-3 print:hidden">
            <Button 
              onClick={copyReceipt}
              variant="outline" 
              className="bg-white hover:bg-slate-50 border-slate-300 text-slate-700"
            >
              {copied ? <Check className="w-4 h-4 mr-2 text-green-600" /> : <Copy className="w-4 h-4 mr-2" />}
              {copied ? "Zkopírováno" : "Kopírovat"}
            </Button>
            <Button 
              onClick={onClose}
              className="bg-slate-900 hover:bg-slate-800 text-white"
            >
              Zavřít
            </Button>
          </div>

           {/* Paper Tear Effect Bottom */}
           <div className="absolute bottom-0 left-0 right-0 h-4 bg-[linear-gradient(45deg,transparent_75%,#f1f5f9_75%),linear-gradient(-45deg,transparent_75%,#f1f5f9_75%)] bg-[size:20px_20px] translate-y-[10px]"></div>
        </div>

      </div>
    </div>
  );
}
