CREATE TABLE IF NOT EXISTS public.kv_store_139017f8 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.kv_store_139017f8 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access" ON public.kv_store_139017f8
  FOR ALL USING (true) WITH CHECK (true);
